// src/components/tailwind-showcase/blocks/sections/testimonials/06-side-by-side.tsx
// @ts-nocheck
"use client";

export default function TailwindBlock() {
  return (
    <section className="bg-paper py-24 sm:py-32">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="mx-auto grid max-w-2xl grid-cols-1 lg:mx-0 lg:max-w-none lg:grid-cols-2">
          <div className="flex flex-col pb-10 sm:pb-16 lg:pr-8 lg:pb-0 xl:pr-20">
            <img
              alt=""
              src="/assets/logo-tqa.jpg"
              className="h-12 self-start"
            />
            <img
              alt=""
              src="/assets/logo-tqa.jpg"
              className="h-12 self-start not-dark:hidden"
            />
            <figure className="mt-10 flex flex-auto flex-col justify-between">
              <blockquote className="text-lg/8 text-charcoal">
                <p>
                  “Amet amet eget scelerisque tellus sit neque faucibus non eleifend. Integer eu praesent at a. Ornare
                  arcu gravida natoque erat et cursus tortor consequat at. Vulputate gravida sociis enim nullam
                  ultricies habitant malesuada lorem ac. Tincidunt urna dui pellentesque sagittis.”
                </p>
              </blockquote>
              <figcaption className="mt-10 flex items-center gap-x-6">
                <img
                  alt=""
                  src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                  className="size-14 rounded-full bg-paper-soft"
                />
                <div className="text-base">
                  <div className="font-semibold text-charcoal">Judith Black</div>
                  <div className="mt-1 text-warm-500">CEO of Tuple</div>
                </div>
              </figcaption>
            </figure>
          </div>
          <div className="flex flex-col border-t border-charcoal/10 pt-10 sm:pt-16 lg:border-t-0 lg:border-l lg:pt-0 lg:pl-8 xl:pl-20">
            <img
              alt=""
              src="/assets/logo-tqa.jpg"
              className="h-12 self-start"
            />
            <img
              alt=""
              src="/assets/logo-tqa.jpg"
              className="h-12 self-start not-dark:hidden"
            />
            <figure className="mt-10 flex flex-auto flex-col justify-between">
              <blockquote className="text-lg/8 text-charcoal">
                <p>
                  “Excepteur veniam labore ullamco eiusmod. Pariatur consequat proident duis dolore nulla veniam
                  reprehenderit nisi officia voluptate incididunt exercitation exercitation elit. Nostrud veniam sint
                  dolor nisi ullamco.”
                </p>
              </blockquote>
              <figcaption className="mt-10 flex items-center gap-x-6">
                <img
                  alt=""
                  src="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
                  className="size-14 rounded-full bg-paper-soft"
                />
                <div className="text-base">
                  <div className="font-semibold text-charcoal">Joseph Rodriguez</div>
                  <div className="mt-1 text-warm-500">CEO of Reform</div>
                </div>
              </figcaption>
            </figure>
          </div>
        </div>
      </div>
    </section>
  )
}

// design/components/tailwind-marketing-v4/vue/sections/testimonials/06-side-by-side.vue
<template>
  <section class="bg-white py-24 sm:py-32 dark:bg-gray-900">
    <div class="mx-auto max-w-7xl px-6 lg:px-8">
      <div class="mx-auto grid max-w-2xl grid-cols-1 lg:mx-0 lg:max-w-none lg:grid-cols-2">
        <div class="flex flex-col pb-10 sm:pb-16 lg:pr-8 lg:pb-0 xl:pr-20">
          <img class="h-12 self-start dark:hidden" src="https://tailwindcss.com/plus-assets/img/logos/tuple-logo-gray-900.svg" alt="" />
          <img class="h-12 self-start not-dark:hidden" src="https://tailwindcss.com/plus-assets/img/logos/tuple-logo-white.svg" alt="" />
          <figure class="mt-10 flex flex-auto flex-col justify-between">
            <blockquote class="text-lg/8 text-gray-900 dark:text-gray-100">
              <p>“Amet amet eget scelerisque tellus sit neque faucibus non eleifend. Integer eu praesent at a. Ornare arcu gravida natoque erat et cursus tortor consequat at. Vulputate gravida sociis enim nullam ultricies habitant malesuada lorem ac. Tincidunt urna dui pellentesque sagittis.”</p>
            </blockquote>
            <figcaption class="mt-10 flex items-center gap-x-6">
              <img class="size-14 rounded-full bg-gray-50 dark:bg-gray-800" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
              <div class="text-base">
                <div class="font-semibold text-gray-900 dark:text-white">Judith Black</div>
                <div class="mt-1 text-gray-500 dark:text-gray-400">CEO of Tuple</div>
              </div>
            </figcaption>
          </figure>
        </div>
        <div class="flex flex-col border-t border-gray-900/10 pt-10 sm:pt-16 lg:border-t-0 lg:border-l lg:pt-0 lg:pl-8 xl:pl-20 dark:border-white/10">
          <img class="h-12 self-start dark:hidden" src="https://tailwindcss.com/plus-assets/img/logos/reform-logo-gray-900.svg" alt="" />
          <img class="h-12 self-start not-dark:hidden" src="https://tailwindcss.com/plus-assets/img/logos/reform-logo-white.svg" alt="" />
          <figure class="mt-10 flex flex-auto flex-col justify-between">
            <blockquote class="text-lg/8 text-gray-900 dark:text-gray-100">
              <p>“Excepteur veniam labore ullamco eiusmod. Pariatur consequat proident duis dolore nulla veniam reprehenderit nisi officia voluptate incididunt exercitation exercitation elit. Nostrud veniam sint dolor nisi ullamco.”</p>
            </blockquote>
            <figcaption class="mt-10 flex items-center gap-x-6">
              <img class="size-14 rounded-full bg-gray-50 dark:bg-gray-800" src="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
              <div class="text-base">
                <div class="font-semibold text-gray-900 dark:text-white">Joseph Rodriguez</div>
                <div class="mt-1 text-gray-500 dark:text-gray-400">CEO of Reform</div>
              </div>
            </figcaption>
          </figure>
        </div>
      </div>
    </div>
  </section>
</template>
