// src/components/tailwind-showcase/blocks/sections/testimonials/08-with-star-rating.tsx
// @ts-nocheck
"use client";

import { StarIcon } from '@heroicons/react/20/solid'

export default function TailwindBlock() {
  return (
    <section className="bg-paper px-6 py-24 sm:py-32 lg:px-8">
      <figure className="mx-auto max-w-2xl">
        <p className="sr-only">5 out of 5 stars</p>
        <div className="flex gap-x-1 text-ember">
          <StarIcon aria-hidden="true" className="size-5 flex-none" />
          <StarIcon aria-hidden="true" className="size-5 flex-none" />
          <StarIcon aria-hidden="true" className="size-5 flex-none" />
          <StarIcon aria-hidden="true" className="size-5 flex-none" />
          <StarIcon aria-hidden="true" className="size-5 flex-none" />
        </div>
        <blockquote className="mt-10 text-xl/8 font-display font-semibold tracking-tight text-charcoal sm:text-2xl/9">
          <p>
            “Qui dolor enim consectetur do et non ex amet culpa sint in ea non dolore. Enim minim magna anim id minim eu
            cillum sunt dolore aliquip. Amet elit laborum culpa irure incididunt adipisicing culpa amet officia
            exercitation. Eu non aute velit id velit Lorem elit anim pariatur.”
          </p>
        </blockquote>
        <figcaption className="mt-10 flex items-center gap-x-6">
          <img
            alt=""
            src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=1024&h=1024&q=80"
            className="size-12 rounded-full bg-paper-soft"
          />
          <div className="text-sm/6">
            <div className="font-semibold text-charcoal">Judith Black</div>
            <div className="mt-0.5 text-warm-500">CEO of Workcation</div>
          </div>
        </figcaption>
      </figure>
    </section>
  )
}

// design/components/tailwind-marketing-v4/vue/sections/testimonials/08-with-star-rating.vue
<template>
  <section class="bg-white px-6 py-24 sm:py-32 lg:px-8 dark:bg-gray-900">
    <figure class="mx-auto max-w-2xl">
      <p class="sr-only">5 out of 5 stars</p>
      <div class="flex gap-x-1 text-indigo-600 dark:text-indigo-400">
        <StarIcon class="size-5 flex-none" aria-hidden="true" />
        <StarIcon class="size-5 flex-none" aria-hidden="true" />
        <StarIcon class="size-5 flex-none" aria-hidden="true" />
        <StarIcon class="size-5 flex-none" aria-hidden="true" />
        <StarIcon class="size-5 flex-none" aria-hidden="true" />
      </div>
      <blockquote class="mt-10 text-xl/8 font-semibold tracking-tight text-gray-900 sm:text-2xl/9 dark:text-white">
        <p>“Qui dolor enim consectetur do et non ex amet culpa sint in ea non dolore. Enim minim magna anim id minim eu cillum sunt dolore aliquip. Amet elit laborum culpa irure incididunt adipisicing culpa amet officia exercitation. Eu non aute velit id velit Lorem elit anim pariatur.”</p>
      </blockquote>
      <figcaption class="mt-10 flex items-center gap-x-6">
        <img class="size-12 rounded-full bg-gray-50 dark:bg-gray-800" src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=1024&h=1024&q=80" alt="" />
        <div class="text-sm/6">
          <div class="font-semibold text-gray-900 dark:text-white">Judith Black</div>
          <div class="mt-0.5 text-gray-600 dark:text-gray-400">CEO of Workcation</div>
        </div>
      </figcaption>
    </figure>
  </section>
</template>

<script setup>
import { StarIcon } from '@heroicons/vue/20/solid'
</script>
