// src/components/tailwind-showcase/blocks/ecommerce/components/promo-sections/02-full-width-with-background-image.tsx
// @ts-nocheck
"use client";

export default function TailwindBlock() {
  return (
    <div className="relative bg-ink px-6 py-32 sm:px-12 sm:py-40 lg:px-16">
      <div className="absolute inset-0 overflow-hidden">
        <img
          alt=""
          src="/assets/logo-tqa.jpg"
          className="size-full object-cover"
        />
      </div>
      <div aria-hidden="true" className="absolute inset-0 bg-ink/50" />
      <div className="relative mx-auto flex max-w-3xl flex-col items-center text-center">
        <h2 className="text-3xl font-bold tracking-tight text-paper sm:text-4xl">Long-term thinking</h2>
        <p className="mt-3 text-xl text-paper">
          We're committed to responsible, sustainable, and ethical manufacturing. Our small-scale approach allows us to
          focus on quality and reduce our impact. We're doing our best to delay the inevitable heat-death of the
          universe.
        </p>
        <a
          href="#"
          className="mt-8 block w-full rounded-md border border-transparent bg-paper px-8 py-3 text-base font-medium text-charcoal hover:bg-paper-soft sm:w-auto"
        >
          Read our story
        </a>
      </div>
    </div>
  )
}

// design/components/ecommerce-v4/vue/components/promo-sections/02-full-width-with-background-image.vue
<template>
  <div class="relative bg-gray-800 px-6 py-32 sm:px-12 sm:py-40 lg:px-16">
    <div class="absolute inset-0 overflow-hidden">
      <img src="https://tailwindcss.com/plus-assets/img/ecommerce-images/home-page-03-feature-section-full-width.jpg" alt="" class="size-full object-cover" />
    </div>
    <div aria-hidden="true" class="absolute inset-0 bg-gray-900/50"></div>
    <div class="relative mx-auto flex max-w-3xl flex-col items-center text-center">
      <h2 class="text-3xl font-bold tracking-tight text-white sm:text-4xl">Long-term thinking</h2>
      <p class="mt-3 text-xl text-white">We're committed to responsible, sustainable, and ethical manufacturing. Our small-scale approach allows us to focus on quality and reduce our impact. We're doing our best to delay the inevitable heat-death of the universe.</p>
      <a href="#" class="mt-8 block w-full rounded-md border border-transparent bg-white px-8 py-3 text-base font-medium text-gray-900 hover:bg-gray-100 sm:w-auto">Read our story</a>
    </div>
  </div>
</template>
