// design/components/tailwind-marketing-v4/vue/sections/cta-sections/07-simple-justified.vue
<template>
  <div class="bg-white dark:bg-gray-900">
    <div class="mx-auto max-w-7xl px-6 py-24 sm:py-32 lg:flex lg:items-center lg:justify-between lg:px-8">
      <h2 class="max-w-2xl text-4xl font-semibold tracking-tight text-gray-900 sm:text-5xl dark:text-white">
        Ready to dive in?
        <br />
        Start your free trial today.
      </h2>
      <div class="mt-10 flex items-center gap-x-6 lg:mt-0 lg:shrink-0">
        <a href="#" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 dark:bg-indigo-500 dark:shadow-none dark:hover:bg-indigo-400 dark:focus-visible:outline-indigo-500"> Get started </a>
        <a href="#" class="text-sm/6 font-semibold text-gray-900 hover:opacity-80 dark:text-gray-100">
          Learn more
          <span aria-hidden="true">→</span>
        </a>
      </div>
    </div>
  </div>
</template>

// design/components/tailwind-marketing-v4/react/sections/cta-sections/07-simple-justified.jsx
export default function Example() {
  return (
    <div className="bg-white dark:bg-gray-900">
      <div className="mx-auto max-w-7xl px-6 py-24 sm:py-32 lg:flex lg:items-center lg:justify-between lg:px-8">
        <h2 className="max-w-2xl text-4xl font-semibold tracking-tight text-gray-900 sm:text-5xl dark:text-white">
          Ready to dive in?
          <br />
          Start your free trial today.
        </h2>
        <div className="mt-10 flex items-center gap-x-6 lg:mt-0 lg:shrink-0">
          <a
            href="#"
            className="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 dark:bg-indigo-500 dark:shadow-none dark:hover:bg-indigo-400 dark:focus-visible:outline-indigo-500"
          >
            {' '}
            Get started{' '}
          </a>
          <a href="#" className="text-sm/6 font-semibold text-gray-900 hover:opacity-80 dark:text-gray-100">
            Learn more
            <span aria-hidden="true">→</span>
          </a>
        </div>
      </div>
    </div>
  )
}
