// src/components/tailwind-showcase/blocks/sections/contact-sections/06-simple-centered.tsx
// @ts-nocheck
"use client";

import { BugAntIcon, ChatBubbleLeftRightIcon, ComputerDesktopIcon } from '@heroicons/react/24/outline'

export default function TailwindBlock() {
  return (
    <div className="isolate bg-paper px-6 py-24 sm:py-32 lg:px-8">
      <div className="mx-auto max-w-2xl sm:text-center">
        <h2 className="text-4xl font-display font-semibold tracking-tight text-balance text-charcoal sm:text-5xl">
          Contact sales
        </h2>
        <p className="mt-2 text-lg/8 text-warm-500">
          Aute magna irure deserunt veniam aliqua magna enim voluptate.
        </p>
      </div>
      <div className="mx-auto mt-20 max-w-lg space-y-16">
        <div className="flex gap-x-6">
          <div className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-ember">
            <ChatBubbleLeftRightIcon aria-hidden="true" className="size-6 text-paper" />
          </div>
          <div>
            <h3 className="text-base/7 font-semibold text-charcoal">Sales support</h3>
            <p className="mt-2 text-base/7 text-warm-500">
              Ut cursus est ut amet. Lobortis eget egestas leo vitae eget porttitor risus blandit. Nunc a in lorem vel
              iaculis porttitor.
            </p>
            <p className="mt-4 text-sm/6 font-semibold">
              <a href="#" className="text-ember">
                Contact us <span aria-hidden="true">&rarr;</span>
              </a>
            </p>
          </div>
        </div>
        <div className="flex gap-x-6">
          <div className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-ember">
            <BugAntIcon aria-hidden="true" className="size-6 text-paper" />
          </div>
          <div>
            <h3 className="text-base/7 font-semibold text-charcoal">Bug reports</h3>
            <p className="mt-2 text-base/7 text-warm-500">
              Expedita qui non ut quia ipsum voluptatum ipsam pariatur. Culpa vitae ipsum minus eius vero quo quibusdam.
            </p>
            <p className="mt-4 text-sm/6 font-semibold">
              <a href="#" className="text-ember">
                Report a bug <span aria-hidden="true">&rarr;</span>
              </a>
            </p>
          </div>
        </div>
        <div className="flex gap-x-6">
          <div className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-ember">
            <ComputerDesktopIcon aria-hidden="true" className="size-6 text-paper" />
          </div>
          <div>
            <h3 className="text-base/7 font-semibold text-charcoal">Technical support</h3>
            <p className="mt-2 text-base/7 text-warm-500">
              Sint aut modi porro consequatur architecto commodi qui consequatur. Dignissimos adipisci minima.
            </p>
            <p className="mt-4 text-sm/6 font-semibold">
              <a href="#" className="text-ember">
                Join our Discord <span aria-hidden="true">&rarr;</span>
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}

// design/components/tailwind-marketing-v4/vue/sections/contact-sections/06-simple-centered.vue
<template>
  <div class="isolate bg-white px-6 py-24 sm:py-32 lg:px-8 dark:bg-gray-900">
    <div class="mx-auto max-w-2xl sm:text-center">
      <h2 class="text-4xl font-semibold tracking-tight text-balance text-gray-900 sm:text-5xl dark:text-white">Contact sales</h2>
      <p class="mt-2 text-lg/8 text-gray-600 dark:text-gray-400">Aute magna irure deserunt veniam aliqua magna enim voluptate.</p>
    </div>
    <div class="mx-auto mt-20 max-w-lg space-y-16">
      <div class="flex gap-x-6">
        <div class="flex size-10 shrink-0 items-center justify-center rounded-lg bg-indigo-600 dark:bg-indigo-500">
          <ChatBubbleLeftRightIcon class="size-6 text-white" aria-hidden="true" />
        </div>
        <div>
          <h3 class="text-base/7 font-semibold text-gray-900 dark:text-white">Sales support</h3>
          <p class="mt-2 text-base/7 text-gray-600 dark:text-gray-400">Ut cursus est ut amet. Lobortis eget egestas leo vitae eget porttitor risus blandit. Nunc a in lorem vel iaculis porttitor.</p>
          <p class="mt-4 text-sm/6 font-semibold">
            <a href="#" class="text-indigo-600 dark:text-indigo-400">Contact us <span aria-hidden="true">&rarr;</span></a>
          </p>
        </div>
      </div>
      <div class="flex gap-x-6">
        <div class="flex size-10 shrink-0 items-center justify-center rounded-lg bg-indigo-600 dark:bg-indigo-500">
          <BugAntIcon class="size-6 text-white" aria-hidden="true" />
        </div>
        <div>
          <h3 class="text-base/7 font-semibold text-gray-900 dark:text-white">Bug reports</h3>
          <p class="mt-2 text-base/7 text-gray-600 dark:text-gray-400">Expedita qui non ut quia ipsum voluptatum ipsam pariatur. Culpa vitae ipsum minus eius vero quo quibusdam.</p>
          <p class="mt-4 text-sm/6 font-semibold">
            <a href="#" class="text-indigo-600 dark:text-indigo-400">Report a bug <span aria-hidden="true">&rarr;</span></a>
          </p>
        </div>
      </div>
      <div class="flex gap-x-6">
        <div class="flex size-10 shrink-0 items-center justify-center rounded-lg bg-indigo-600 dark:bg-indigo-500">
          <ComputerDesktopIcon class="size-6 text-white" aria-hidden="true" />
        </div>
        <div>
          <h3 class="text-base/7 font-semibold text-gray-900 dark:text-white">Technical support</h3>
          <p class="mt-2 text-base/7 text-gray-600 dark:text-gray-400">Sint aut modi porro consequatur architecto commodi qui consequatur. Dignissimos adipisci minima.</p>
          <p class="mt-4 text-sm/6 font-semibold">
            <a href="#" class="text-indigo-600 dark:text-indigo-400">Join our Discord <span aria-hidden="true">&rarr;</span></a>
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { BugAntIcon, ChatBubbleLeftRightIcon, ComputerDesktopIcon } from '@heroicons/vue/24/outline'
</script>
